name: Build Plugin

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew make
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Yanhh3D-Plugin
          path: "**/*.zip"
